FROM php:8.4.4-fpm-alpine3.21

RUN apk update \
&&  apk add --no-cache \
    build-base \
    postgresql-dev \
    autoconf \
    msmtp

RUN docker-php-ext-install pdo pdo_pgsql

RUN ln -sf /usr/bin/msmtp /usr/bin/sendmail \
&&  ln -sf /usr/bin/msmtp /usr/sbin/sendmail

WORKDIR /var/www/html

ENV DEBUG=true

CMD ["php-fpm"]

