FROM php:8.4.4-fpm-alpine3.21

RUN apk update \
&&  apk add --no-cache build-base postgresql-dev autoconf msmtp libpng-dev \
&&  ln -sf /usr/bin/msmtp /usr/bin/sendmail \
&&  ln -sf /usr/bin/msmtp /usr/sbin/sendmail

RUN docker-php-ext-install pdo pdo_pgsql gd

RUN mkdir -m 0755 -p /var/lib/camagru \
&&  chown www-data:www-data /var/lib/camagru

WORKDIR /var/www/html

ENV DEBUG=true
ENV APP_ENV=development

CMD ["php-fpm"]
